up_product_category : list[dict[str,str]] = [
    {
        "product_name": "चुनें",
        "value": "0"
    },
    {
        "product_name": "खाद्दान्न",
        "value": "01"
    },
    {
        "product_name": "दलहन",
        "value": "02"
    },
    {
        "product_name": "तिलहन",
        "value": "03"
    },
    {
        "product_name": "मसाले",
        "value": "04"
    },
    {
        "product_name": "सब्जिया",
        "value": "05"
    },
    {
        "product_name": "फल",
        "value": "06"
    },
    {
        "product_name": "पशु उत्पाद",
        "value": "07"
    },
    {
        "product_name": "खाल चमड़ा",
        "value": "08"
    },
    {
        "product_name": "रेशेवाली",
        "value": "09"
    },
    {
        "product_name": "चारा",
        "value": "10"
    },
    {
        "product_name": "जंगली उत्पाद",
        "value": "11"
    },
    {
        "product_name": "मीट",
        "value": "12"
    },
    {
        "product_name": "अन्य",
        "value": "13"
    },
    {
        "product_name": "प्रसंस्कृत उत्पाद",
        "value": "14"
    }
]
up_mandi_code : dict[str,str] ={
    "Amethi": "ct_Amethi",
    "Jafarganj": "ct_Jafarganj",
    "Jayas": "ct_Jayas",
    "Ambedkarnagar": "ct_Ambedkarnagar",
    "Amroha": "ct_Amroha",
    "Hasanpur": "ct_Hasanpur",
    "Ayodhya": "ct_Ayodhya",
    "Rudauli": "ct_Rudauli",
    "Aligarh": "ct_Aligarh",
    "Chharra": "ct_Chharra",
    "Khair": "ct_Khair",
    "Achnera": "ct_Achnera",
    "Agra": "ct_Agra",
    "Fatehabad": "ct_Fatehabad",
    "FatehpurSikri": "ct_FatehpurSikri",
    "Jagnair": "ct_Jagnair",
    "Khairagarh": "ct_Khairagarh",
    "Shamsabad": "ct_Shamsabad",
    "Azamgarh": "ct_Azamgarh",
    "Bharthana": "ct_Bharthana",
    "Etawah": "ct_Etawah",
    "Jaswantnagar": "ct_Jaswantnagar",
    "Bangarmau": "ct_Bangarmau",
    "Purwa": "ct_Purwa",
    "Unnao": "ct_Unnao",
    "Aliganj": "ct_Aliganj",
    "Etah": "ct_Etah",
    "Achalda": "ct_Achalda",
    "Auraiya": "ct_Auraiya",
    "Dibiyapur": "ct_Dibiyapur",
    "Chhibramau": "ct_Chhibramau",
    "Kannuj": "ct_Kannuj",
    "Kushinagar": "ct_Kushinagar",
    "Jhinjhak": "ct_Jhinjhak",
    "Pukhrayan": "ct_Pukhrayan",
    "Rura": "ct_Rura",
    "Chaubepur": "ct_Chaubepur",
    "Kanpur": "ct_Kanpur",
    "Uattripura": "ct_Uattripura",
    "Varipal": "ct_Varipal",
    "Kasganj": "ct_Kasganj",
    "Ajuha": "ct_Ajuha",
    "Bharvari": "ct_Bharvari",
    "Kaushambi": "ct_Kaushambi",
    "Ghaziabad": "ct_Ghaziabad",
    "Muradnagar": "ct_Muradnagar",
    "Gazipur": "ct_Gazipur",
    "Jangipur": "ct_Jangipur",
    "Gonda": "ct_Gonda",
    "Karnailganj": "ct_Karnailganj",
    "Nawabganj": "ct_Nawabganj",
    "Chaurichaura": "ct_Chaurichaura",
    "Gorakhpur": "ct_Gorakhpur",
    "Sahjanwa": "ct_Sahjanwa",
    "Dadri": "ct_Dadri",
    "Dankaur": "ct_Dankaur",
    "Noida": "ct_Noida",
    "Chandauli": "ct_Chandauli",
    "Chitrakoot": "ct_Chitrakoot",
    "Jalaun": "ct_Jalaun",
    "Kadaura": "ct_Kadaura",
    "Kalpi": "ct_Kalpi",
    "Konch": "ct_Konch",
    "Orai": "ct_Orai",
    "Jaunpur": "ct_Jaunpur",
    "Mugrabadshahpur": "ct_Mugrabadshahpur",
    "Shahganj": "ct_Shahganj",
    "Chirgaon": "ct_Chirgaon",
    "Gurusarai": "ct_Gurusarai",
    "Jhansi": "ct_Jhansi",
    "Mauranipur": "ct_Mauranipur",
    "Moth": "ct_Moth",
    "Devariya": "ct_Devariya",
    "Pratapgarh": "ct_Pratapgarh",
    "Jasra": "ct_Jasra",
    "Lendiyari": "ct_Lendiyari",
    "Prayagraj": "ct_Prayagraj",
    "Sirsa": "ct_Sirsa",
    "Pilibhit": "ct_Pilibhit",
    "Puranpur": "ct_Puranpur",
    "Vishalpur": "ct_Vishalpur",
    "Bindki": "ct_Bindki",
    "Fatehpur": "ct_Fatehpur",
    "Jahanabad": "ct_Jahanabad",
    "Khaga": "ct_Khaga",
    "Kishanpur": "ct_Kishanpur",
    "Farrukhabad": "ct_Farrukhabad",
    "Kamalganj": "ct_Kamalganj",
    "Kayamganj": "ct_Kayamganj",
    "Mohamadabad": "ct_Mohamadabad",
    "Firozabad": "ct_Firozabad",
    "Shikohabad": "ct_Shikohabad",
    "Sirsaganj": "ct_Sirsaganj",
    "Tundla": "ct_Tundla",
    "Badayoun": "ct_Badayoun",
    "Bilsi": "ct_Bilsi",
    "Ujhani": "ct_Ujhani",
    "Visoli": "ct_Visoli",
    "Wazirganj": "ct_Wazirganj",
    "Anwala": "ct_Anwala",
    "Bahedi": "ct_Bahedi",
    "Bareilly": "ct_Bareilly",
    "Anoopnagar": "ct_Anoopnagar",
    "Bulandshahar": "ct_Bulandshahar",
    "Dibai": "ct_Dibai",
    "Gulavati": "ct_Gulavati",
    "Jahangirabad": "ct_Jahangirabad",
    "Khurja": "ct_Khurja",
    "Sikanderabad": "ct_Sikanderabad",
    "Sikarpur": "ct_Sikarpur",
    "Siyana": "ct_Siyana",
    "Balrampur": "ct_Balrampur",
    "Panchpedwa": "ct_Panchpedwa",
    "Tulsipur": "ct_Tulsipur",
    "Baliya": "ct_Baliya",
    "Rasda": "ct_Rasda",
    "Basti": "ct_Basti",
    "Bahraich": "ct_Bahraich",
    "Nanpara": "ct_Nanpara",
    "Payagpur": "ct_Payagpur",
    "Bagpat": "ct_Bagpat",
    "Baraut": "ct_Baraut",
    "Khekda": "ct_Khekda",
    "Atarra": "ct_Atarra",
    "Baberu": "ct_Baberu",
    "Banda": "ct_Banda",
    "Barabanki": "ct_Barabanki",
    "Safdarganj": "ct_Safdarganj",
    "Bijnaur": "ct_Bijnaur",
    "Chaandpur": "ct_Chaandpur",
    "Kiratpur": "ct_Kiratpur",
    "Najibabad": "ct_Najibabad",
    "Bhadohi": "ct_Bhadohi",
    "Gopiganj": "ct_Gopiganj",
    "Doharighat": "ct_Doharighat",
    "Kopaganj": "ct_Kopaganj",
    "Khatauli": "ct_Khatauli",
    "Muzzafarnagar": "ct_Muzzafarnagar",
    "Kosikalan": "ct_Kosikalan",
    "Mathura": "ct_Mathura",
    "Bewar": "ct_Bewar",
    "Ghiraur": "ct_Ghiraur",
    "Mainpuri": "ct_Mainpuri",
    "Mawana": "ct_Mawana",
    "Meerut": "ct_Meerut",
    "Sardhana": "ct_Sardhana",
    "Muradabad": "ct_Muradabad",
    "Anandnagar": "ct_Anandnagar",
    "Gadaura": "ct_Gadaura",
    "Mahrajganj": "ct_Mahrajganj",
    "Nautanva": "ct_Nautanva",
    "Partaval": "ct_Partaval",
    "Charkhari": "ct_Charkhari",
    "Mahoba": "ct_Mahoba",
    "Ahirora": "ct_Ahirora",
    "Mirzapur": "ct_Mirzapur",
    "Milak": "ct_Milak",
    "Rampur": "ct_Rampur",
    "Shahbad": "ct_Shahbad",
    "Vilaspur": "ct_Vilaspur",
    "Bachranwa": "ct_Bachranwa",
    "Lalganj": "ct_Lalganj",
    "Raibarely": "ct_Raibarely",
    "Lucknow": "ct_Lucknow",
    "Golagokarnnath": "ct_Golagokarnnath",
    "Lakhimpurkhiri": "ct_Lakhimpurkhiri",
    "Mohammdi": "ct_Mohammdi",
    "Paliyakala": "ct_Paliyakala",
    "Tikoniya": "ct_Tikoniya",
    "Lalitpur": "ct_Lalitpur",
    "Mehrauni": "ct_Mehrauni",
    "Varanasi": "ct_Varanasi",
    "Bhinga": "ct_Bhinga",
    "Shamli": "ct_Shamli",
    "Thanabhawan": "ct_Thanabhawan",
    "Jalalabad": "ct_Jalalabad",
    "Puwanya": "ct_Puwanya",
    "Shahjahanpur": "ct_Shahjahanpur",
    "Tilhar": "ct_Tilhar",
    "Khalilabad": "ct_Khalilabad",
    "Behjoi": "ct_Behjoi",
    "Chandausi": "ct_Chandausi",
    "Sambhal": "ct_Sambhal",
    "Sultanpur": "ct_Sultanpur",
    "Chhutmalpur": "ct_Chhutmalpur",
    "Devband": "ct_Devband",
    "Gangoh": "ct_Gangoh",
    "Rampurmaniharan": "ct_Rampurmaniharan",
    "Saharanpur": "ct_Saharanpur",
    "Sahiyapur": "ct_Sahiyapur",
    "Siddharthnagar": "ct_Siddharthnagar",
    "Wansi": "ct_Wansi",
    "Mehmoodabad": "ct_Mehmoodabad",
    "Sitapur": "ct_Sitapur",
    "Viswan": "ct_Viswan",
    "Robertsganj": "ct_Robertsganj",
    "Baruasumerpur": "ct_Baruasumerpur",
    "Hamirpur": "ct_Hamirpur",
    "Kurara": "ct_Kurara",
    "Maudaha": "ct_Maudaha",
    "Muskara": "ct_Muskara",
    "Rath": "ct_Rath",
    "Hardoi": "ct_Hardoi",
    "Madhoganj": "ct_Madhoganj",
    "Sandi": "ct_Sandi",
    "Sandila": "ct_Sandila",
    "Shahabad": "ct_Shahabad",
    "Hathras": "ct_Hathras",
    "Shadabad": "ct_Shadabad",
    "Sikandrau": "ct_Sikandrau",
    "Hapur": "ct_Hapur"
}